
resource.AddFile( "materials/fwkzt/emojis/blue_shift.png" )
resource.AddFile( "materials/fwkzt/emojis/gmod.png" )
resource.AddFile( "materials/fwkzt/emojis/headcrab.png" )
resource.AddFile( "materials/fwkzt/emojis/hl2.png" )
resource.AddFile( "materials/fwkzt/emojis/isaac.png" )
resource.AddFile( "materials/fwkzt/emojis/jim_smile.png" )
resource.AddFile( "materials/fwkzt/emojis/kleiner.png" )
resource.AddFile( "materials/fwkzt/emojis/lenny.png" )
resource.AddFile( "materials/fwkzt/emojis/lennycry.png" )
resource.AddFile( "materials/fwkzt/emojis/ogkleiner.png" )
resource.AddFile( "materials/fwkzt/emojis/omegalol.png" )
resource.AddFile( "materials/fwkzt/emojis/pat_evil.png" )
resource.AddFile( "materials/fwkzt/emojis/pat_eyes.png" )
resource.AddFile( "materials/fwkzt/emojis/poggers.png" )
resource.AddFile( "materials/fwkzt/emojis/rofl_laugh.png" )
resource.AddFile( "materials/fwkzt/emojis/rofl_stare.png" )
resource.AddFile( "materials/fwkzt/emojis/steve_smug.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Ameno.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/begone_thot.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Clown.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/clown_nutcracker.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/consume.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/cool_santa.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/creeper.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/deadspace2.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/decap.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/disappointment.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Dorime.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/edgy_mka.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/evil_pepega.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/finger.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/fwkzt.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/gmod.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/gnr.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/GP.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Hammer.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/headbutt.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/heavydutybrick.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/jack_o_clown.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/jerry_rage.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/jerry_surprised.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/joe_confused.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/lua.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/mka.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/MOW.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/muscles_mouse.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/nice.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/otamatone.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/otamatone_evil.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pardon.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/patrick_nani.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/patrick_pog.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/patrick_slump.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pepe_hands.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pepe_hands_santa.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pepe_nani.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pepe_ok.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/pepe_woke.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/PogChamp.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/PumpkinPepe.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/roblox.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/robot_mka.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/sans_thonk.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/simp.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/sirmack.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/skipper.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/SquidDab.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/steam.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/steve_dab.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/stop_pls.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/thisgonbegood.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Thumbsup.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/tomstare.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/tom_confused.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/tom_happy.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/tom_stare.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/triggered.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/uncle_pecos.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/wikihowsweat.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/wreath.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/xmas_reverse.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/yikes.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/you_fool.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/zcade.png" )
resource.AddFile( "materials/fwkzt/emojis/sub/Zombie.png" )
resource.AddFile( "materials/fwkzt/emojis/thonk.png" )

--TODO: loop through emojis folder and resource add all jpeg/pngs.

hook.Add( "PlayerSay", "FilterEmonjis", function( ply, text )

	if ply.HasChatTag and ply:HasChatTag() then
		PrintMessage(HUD_PRINTCONSOLE, "("..ply:SteamID()..") ".."["..ply:GetChatTag().."] "..ply:Nick().. ": "..text)
	else
		PrintMessage(HUD_PRINTCONSOLE, "("..ply:SteamID()..") "..ply:Nick().. ": "..text)
	end
	
	--TODO: only pass non url text.
	--[[if string.match( text, "^[https//:]+%w+%.%w+[/%w%.]+$") then
		return " "
	end]]
end )